### ISSUE TITLE
catching invalid GIS coordinates exception

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#42]
In the current editor, when inputting some wrong coordinates the editor crashes, the console says:

```
react-dom.production.min.js:209 Error: Invalid LatLng object: (32.790299, 79.001794, 79.16593551635744)
    at new U (LatLng.js:32:9)
    at H (LatLng.js:123:11)
    at t.initialize (Map.js:153:17)
    at new t (Class.js:22:20)
    at MapContainer.js:10:24
    at ls (react-dom.production.min.js:211:320)
    at xl (react-dom.production.min.js:257:303)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Zi (react-dom.production.min.js:122:325)
    at Tl (react-dom.production.min.js:257:58)
is @ react-dom.production.min.js:209
scheduler.production.min.js:14 Uncaught Error: Invalid LatLng object: (32.790299, 79.001794, 79.16593551635744)
    at new U (LatLng.js:32:9)
    at H (LatLng.js:123:11)
    at t.initialize (Map.js:153:17)
    at new t (Class.js:22:20)
    at MapContainer.js:10:24
    at ls (react-dom.production.min.js:211:320)
    at xl (react-dom.production.min.js:257:303)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Zi (react-dom.production.min.js:122:325)
    at Tl (react-dom.production.min.js:257:58)
```

**Comment by berger-n** [comment]
fixed: https://editor.bdrc.io/edit/bdr:G1NB4/bds:PlaceShape

![image](https://user-images.githubusercontent.com/33383857/204333080-05a528c3-dc6e-4149-bb42-641b6036067e.png)

**Comment by eroux** [comment]
thanks! Another issue though: we only allow 6 digits after the dot in the coordinates, and leaflet gives 14 (!), can we make it give only 6?

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/edit/bdr:G1NB4/bds:PlaceShape

![simplescreenrecorder-2022-12-01_11 39 40 mkv](https://user-images.githubusercontent.com/33383857/205032589-f6a0f4d6-312b-46a9-a5d5-782421485fca.gif)

**Comment by eroux** [comment]
perfect, thanks!
